# Generated by Django 6.0.2 on 2026-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_collection_collectionpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
