"""
Django settings for lean_forum project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", default='django-insecure-dev-placeholder-change-me')


def env_flag(name, default=False):
    """解析布尔型环境变量：只有 1/true/yes/on 才算真。

    不能用 bool(os.environ.get(name, default))：布尔字符串的坑在于 bool("0") 是 True，
    会让 DEBUG=0 反而打开调试模式（线上就会把堆栈和配置暴露出去）。
    """
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DEBUG", default=False)

# 上传文件（头像、帖子图片）与静态文件默认由 Django 直接提供，
# 让小站在没有 nginx 的情况下也能正常跑；
# 如果前面已经有 nginx/CDN 托管 /media/、/static/，把对应开关设为 0 交给前置服务器。
SERVE_MEDIA = env_flag("SERVE_MEDIA", default=True)
SERVE_STATIC = env_flag("SERVE_STATIC", default=True)


# 个人主页上的「IP 归属地」。
#
# 原来是一个让用户自己手填的「所在地」文本框，现在改成按 IP 自动算。
# 只取到省/市一级，完整 IP 既不展示也不落库（Profile.last_ip 只用来判断
# 归属地要不要重算，不对外输出）。

# 前面有几层反向代理。0 = Django 直接对外（取 REMOTE_ADDR）；
# 1 = 一层 nginx（取 X-Forwarded-For 里紧挨着我们的那一项）。
# 注意：X-Forwarded-For 客户端可以伪造，所以只信右边（离我们最近）的那几跳。
FORUM_TRUSTED_PROXY_COUNT = int(os.environ.get("FORUM_TRUSTED_PROXY_COUNT", default="0"))

# 归属地查询接口，{ip} 会被替换成客户端 IP。
# 默认用 ip-api.com：免费、无需 key、支持中文返回（lang=zh-CN）。
# 想换成自建服务或离线库，改这个环境变量；留空则完全不做在线查询
# （那样归属地只会对内网地址显示「本地网络」，其余留空）。
FORUM_GEOIP_API = os.environ.get(
    "FORUM_GEOIP_API",
    default="http://ip-api.com/json/{ip}?lang=zh-CN&fields=status,country,regionName,city",
)

# 查询超时（秒）。归属地是锦上添花，超时就放弃，不能拖慢登录。
FORUM_GEOIP_TIMEOUT = float(os.environ.get("FORUM_GEOIP_TIMEOUT", default="2"))


# ALLOWED_HOSTS 通过环境变量配置（逗号分隔）；
# 未设置时默认 ["*"]，如需严格限制生产域名请显式传入 ALLOWED_HOSTS
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", default="*").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'md_editor',
    'webpush',
    'forum',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 通过 CORS_ALLOWED_ORIGINS 环境变量配置生产来源（逗号分隔）
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if o.strip()
]

# 仅在 DEBUG 且未配置 CORS_ALLOWED_ORIGINS 时允许全部来源，
# 防止生产部署遗忘来源列表带来的 CSRF/CORS 风险
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS

# 仅允许在配置了可信来源时携带凭证
CORS_ALLOW_CREDENTIALS = bool(CORS_ALLOWED_ORIGINS)

ROOT_URLCONF = 'lean_forum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lean_forum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

MEDIA_URL = '/media/'

LOGIN_URL= 'login'


# please set your own VAPID keys here in production
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.environ.get("VAPID_PUBLIC_KEY", default="BO2V65XdP_gUebE7mEkw8gdO0xOcCInw7NAjnjO1n1hUI0oOklzYBA4lAMIA7iU5-NkHtOM__XnhmL7DGlfcLQc"),
    "VAPID_PRIVATE_KEY": os.environ.get("VAPID_PRIVATE_KEY", default="-JvRFwRAYw4gb6nhLvCrXzEBDOoMES_QVxWibh2KFek"),
    "VAPID_ADMIN_EMAIL": os.environ.get("VAPID_ADMIN_EMAIL", default="admin@example.com")
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
}
